name: golangci-lint
on:
  workflow_dispatch: {}
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - uses: actions/checkout@v3
    - name: lint-host-ctr
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        working-directory: sources/host-ctr
    - name: lint-ecs-gpu-init
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        working-directory: sources/ecs-gpu-init
